
[package]
name = "jsonrpc"
version = "0.0.1"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]


[lib]
name = "jsonrpc"
path = "src/lib.rs"

[dependencies.http]
git = "https://github.com/chris-morgan/rust-http.git"

