
[package]
name		= "jsonrpc"
version		= "0.7.2"
authors		= ["Andrew Poelstra <apoelstra@wpsoftware.net>"]
license		= "CC0-1.0"
homepage	= "https://github.com/apoelstra/rust-jsonrpc/"
repository	= "https://github.com/apoelstra/rust-jsonrpc/"
documentation	= "https://www.wpsoftware.net/rustdoc/jsonrpc/"
description	= "Rust support for the JSON-RPC 2.0 protocol"
keywords	= [ "protocol", "json", "http", "jsonrpc" ]
readme		= "README.md"

[lib]
name = "jsonrpc"
path = "src/lib.rs"

[dependencies]
hyper = "0.6"
serde = "0.6"
strason = "0.3"


